name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d testing"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.8

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy .env file
        run: cp .env.example .env

      - name: Configure .env
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=testing" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Enable PostgreSQL extensions
        run: |
          PGPASSWORD=password psql -h 127.0.0.1 -U user -d testing -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
          PGPASSWORD=password psql -h 127.0.0.1 -U user -d testing -c "CREATE EXTENSION IF NOT EXISTS \"pgcrypto\";"

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
